---
- name: Copy configs to hive/conf
  template:
    src: "templates/hive/conf/{{ item }}"
    dest: "{{ hive_home }}/conf/{{ item }}"
    owner: "{{ hadoop_user }}"
  with_items:
    - hive-site.xml
    - hive-log4j2.properties
    - hive-env.sh

- name: add PATH to hive/bin in .bashrc
  lineinfile:
#    dest: '{{ hadoop_user_home }}/.bashrc'
    dest: '/etc/bash.bashrc'
    line: 'export PATH=$PATH:{{ hive_home }}/bin # HIVE-BIN-PATH'
    regexp: '# HIVE-BIN-PATH'



