---

- name: Copy libs
  copy:
    src: "files/hive/lib/"
    dest: "{{ hive_home }}/lib/"

#- name: Copy additional jars to Hive libs
#  template:
#    src: "{{ item }}"
#    dest: "{{ hive_home }}/lib/{{ item }}"
#    owner: "{{ hadoop_user }}"
#  with_fileglob:
#    - files/hive/lib/*

- name: Copy configs to hive/conf
  template:
    src: "templates/hive/conf/{{ item }}"
    dest: "{{ hive_home }}/conf/{{ item }}"
    owner: "{{ hadoop_user }}"
  with_items:
  - hive-site.xml
  - hive-log4j2.properties
  - hive-env.sh

- name: add HIVE_HOME to hive/bin in .bashrc
  lineinfile:
#    dest: '{{ hadoop_user_home }}/.bashrc'
    dest: '/etc/csh.cshrc'
    line: 'export HIVE_HOME={{ hive_home }}'
    regexp: '^(# *)?export HIVE_HOME'


- name: add PATH to hive/bin in .bashrc
  lineinfile:
#    dest: '{{ hadoop_user_home }}/.bashrc'
    dest: '/etc/csh.cshrc'
    line: 'export PATH=$PATH:{{ hive_home }}/bin # HIVE-BIN-PATH'
    regexp: '# HIVE-BIN-PATH'

- name: add PATH to hive/lib in .bashrc
  lineinfile:
#    dest: '{{ hadoop_user_home }}/.bashrc'
    dest: '/etc/csh.cshrc'
    line: 'export PATH=$PATH:{{ hive_home }}/lib # HIVE-LIB-PATH'
    regexp: '# HIVE-LIB-PATH'


