---
- name: download hive
  get_url:
    url: '{{ hive_mirrors|random }}/apache-hive-{{ hive_version }}-bin.tar.gz'
    dest: '{{ hive_home }}-apache-hive-{{ hive_version }}-bin.tar.gz'
    force: no
  register: result
  until: result|success
  retries: 5
  delay: 2
  sudo: yes

- name: unpack Hive
  sudo: yes
  command: bash -c "cd /opt && tar xzf {{ hive_home }}-apache-hive-{{ hive_version }}-bin.tar.gz" creates={{ hive_home }}-apache-hive-{{ hive_version }}

- name: make a link /opt/hive
  file: state=link src=/opt/apache-hive-{{ hive_version }}-bin dest={{ hive_home }}

- name: chown hive folder owner to hive user
  file:
    path: '/opt/apache-hive-{{ hive_version }}-bin'
    owner: '{{ hadoop_user }}'
    group: '{{ hadoop_group }}'
    recurse: yes
