---
############# In hive role only copy hive and configs, do not start any services
# Services will be started later, when tez and llap are configured
#####################################################################

- name: Add a fast check to speed reconfiguration
  stat: path={{ hive_home }}-apache-hive-{{ hive_version }}-bin
  register: hive_installed


- name: Download and copy to /opt/hive
  include: download.yml

- name: Open hive ports
  include: open-ports.yml

- name: Copy configs and
  include: configure.yml

- name: Autostart hiveserver2 daemon
  include: autostart.yml


