---

- name: Copy service files
  template:
    src: 'templates/etc/systemd/system/zookeeper.service'
    dest: '/etc/systemd/system/zookeeper.service'
    force: true
    ##mode: 0755
- name: Restart zookeeper daemon
  systemd:
    name: 'zookeeper'
    enabled: yes
    state: restarted
    daemon_reload: yes

#- name: Restart zookeeper daemon
#  systemd:
#    name: zookeeper
#    enabled: yes
#    state: restarted
#    daemon_reload: true
