---

- name: Add a fast check to speed reconfiguration
  stat: path=/opt/zookeeper
  register: zk_installed

- name: Open zk ports
  include: open-ports.yml

- name: Download and copy files to destination
  include: download.yml
  when: not zk_installed.stat.exists
#
- name: Configuration changes
  include: configure.yml
#
- name: Autostart set up
  include: autostart.yml

