---

# Servers listen on three ports:
# 2181 for client connections;
# 2888 for follower connections, if they are the leader;
# 3888 for other server connections during the leader election phase .

- name: Open zookeeper ports
  iptables: chain=INPUT jump=ACCEPT protocol=tcp destination_port={{item}}
  ignore_errors: no
  with_items:
  - 2181
  - 2888
  - 3888

- name: Open all ports from ip {{ item.1 }} in the firewall
  iptables: chain=INPUT jump=ACCEPT protocol=tcp source {{ item.1 }}
  ignore_errors: yes
  with_together:
      - groups.all
      - ansible_all_ipv4_addresses

# Example action to restart service httpd, in all cases
- service:
    name: networking
    state: restarted