---

- name: Copy service files
  template:
    src: 'templates/etc/systemd/system/{{ item }}'
    dest: '/etc/systemd/system/{{ item }}'
    force: true
  with_items:
      - flink.service

- name: Activate daemons
  service:
    name: '{{ item }}'
    enabled: yes
    state: reloaded
    state: started
  with_items:
      - flink
