---

- name: Copy service files
  template:
    src: 'templates/etc/systemd/system/{{ item }}'
    dest: '/etc/systemd/system/{{ item }}'
    force: true
  with_items:
    - flink-jobmanager.service
    - flink-taskmanager.service


- name: Activate Flink job managers on masters
  when: hadoop_type_of_node == "hadoop_master"
  service:
    name: flink-jobmanager
    enabled: yes
    state: reloaded
    state: started

- name: Activate Flink task managers on slaves
  service:
    name: flink-taskmanager
    enabled: yes
    state: reloaded
    state: started
