---

- name: Copy flink config files
  template:
    src: 'templates/flink/conf/{{ item }}'
    dest: '{{ flink_home }}/conf/{{ item }}'
    force: yes
    owner: '{{ flink_user }}'
    group: '{{ flink_group }}'
  with_items:
    - flink-conf.yaml
    - masters
    - slaves
