---
- name: Add a fast check to speed reconfiguration
  stat: path={{ flink_home }}
  register: flink_installed

- name: Open flink ports
  include: open-ports.yml

- name: Download and copy files to destination
  include: download.yml
  when: not flink_installed.stat.exists

- name: Update flink configs
  include: configure.yml

- name: Autostart set up
  include: autostart.yml

