---

- name: Copy service files
  template:
    src: 'templates/etc/systemd/system/{{ item }}'
    dest: '/etc/systemd/system/{{ item }}'
    #sudo: yes
    force: true
    #mode: 0755
  with_items:
      - hadoop-namenode.service
      - hadoop-secondarynamenode.service
      - hadoop-datanode.service
      - yarn-nodemanager.service
      - yarn-resourcemanager.service
      - yarn-proxyserver.service

- name: stop services
  service:
    name: '{{ item }}'
    enabled: yes
    state: stopped
  with_items:
      - hadoop-namenode.service
      - hadoop-secondarynamenode.service
      - hadoop-datanode.service
      - yarn-nodemanager.service
      - yarn-resourcemanager.service
      - yarn-proxyserver.service

- name: Activate name node
  when: "'hadoop_namenode' in group_names"
  service:
    name: '{{ item }}'
    enabled: yes
    state: started
  with_items:
      - hadoop-namenode
      - hadoop-secondarynamenode

- name: Activate resource manager
  when: "'hadoop_resourcemanager' in group_names"
  service:
    name: '{{ item }}'
    enabled: yes
    state: started
  with_items:
      - yarn-resourcemanager
      - yarn-proxyserver

- name: Activate datanode and yarn nodemanager on workers
  when: '"hadoop_workers" in group_names'
  service:
    name: '{{ item }}'
    enabled: yes
    state: reloaded
  with_items:
      - hadoop-datanode
      - yarn-nodemanager

#
#- name: Activate master daemons
#  when: '"hadoop_master" in hadoop_type_of_node'
#  service:
#    name: '{{ item }}'
#    enabled: yes
#    state: reloaded
#    state: started
#  with_items:
#      - hadoop-namenode
#      - hadoop-secondarynamenode
#      - yarn-resourcemanager
#      - yarn-proxyserver
#
#- name: Activate slave daemons
#  when: '"hadoop_slave" in hadoop_type_of_node'
#  service:
#    name: '{{ item }}'
#    enabled: yes
#    state: reloaded
#    state: started
#  with_items:
#      - hadoop-datanode
#      - yarn-nodemanager
