---
# Create hadoop user
- name: add hadoop group
  group: name={{ hadoop_group }}

- name: add hadoop user
  user: name={{ hadoop_user}} group={{ hadoop_group }} password={{ hadoop_user_pass }} home={{ hadoop_user_home }} shell=/bin/bash


- name: install system updates for centos systems
  yum: name={{ item }} state=present update_cache=yes
  when: ansible_distribution == "CentOS"
  with_items:
    - wget
    - tar
    - gzip
    - unzip

- name: Apt install {{ item }}
  action: apt pkg={{ item }} state=installed update_cache=yes cache_valid_time=604800
  when: ansible_distribution == "Ubuntu"
  with_items:
  - wget
  - tar
  - gzip
  - unzip

- name: install java for Ubuntu
  apt: name={{ java_package }} state=present
  when: ansible_distribution == "Ubuntu"

- name: install java for CentOS
  yum: name={{ java_package }} state=present
  when: ansible_distribution == "CentOS"

- name: set hadoop_installed flag
  stat: path='{ hadoop_home }}-{{ hadoop_version }}.tar.gz'
  register: hadoop_installed


- name: download hadoop
  get_url:
    url: '{{ hadoop_mirrors|random }}'
    dest: '{{ hadoop_home }}-{{ hadoop_version }}.tar.gz'
    force: no
  register: result
  until: result|success
  retries: 5
  delay: 2
  sudo: yes
  when: not hadoop_installed.stat.exists


- name: extract hadoop tarball
  command: '/usr/bin/env tar xf hadoop-{{ hadoop_version }}.tar.gz'
  args:
    chdir: '{{ hadoop_home }}/..'
    creates: '{{ hadoop_home }}/hadoop-{{ hadoop_version }}'
  sudo: yes


- name: chown to hadoop user
  file:
    dest: '{{ hadoop_home }}-{{ hadoop_version }}'
    owner: '{{ hadoop_user }}'
    group: '{{ hadoop_group }}'
    recurse: yes

- name: create link to hadoop
  file:
    src: '{{ hadoop_home }}-{{ hadoop_version }}'
    dest: '{{ hadoop_home }}'
    state: link
    owner: '{{ hadoop_user }}'
    group: '{{ hadoop_group }}'

- name: Creates directory
  file:
    path: '{{ hadoop_home }}-{{ hadoop_version }}/logs'
    state: directory
    owner: '{{ hadoop_user }}'
    group: '{{ hadoop_group }}'
    mode: 0777



