---

- name: Download and copy files to destination
  include: download.yml

- name: Open hadoop ports
  include: open-ports.yml

- name: Configuration changes
  include: configure.yml

- name: Autostart set up
  include: autostart.yml


