---

- name: Creates directory
  file:
    path: '{{ hadoop_home }}-{{ hadoop_version }}/logs'
    state: directory
    owner: '{{ hadoop_user }}'
    group: '{{ hadoop_group }}'
    mode: 0664
    force: yes


- name: Add a fast check to speed reconfiguration
  stat: path=/opt/hadoop
  register: hadoop_installed

- name: Open hadoop ports
  include: open-ports.yml

- name: Download and copy files to destination
  include: download.yml
  when: not hadoop_installed.stat.exists

- name: Configuration changes
  include: configure.yml

- name: Autostart set up
  include: autostart.yml

