---
- name: Add a fast check to speed reconfiguration
  stat: path={{ ignite_home }}
  register: ignite_installed

- name: Open ignite ports
  include: open-ports.yml

- name: Download and copy files to destination
  include: download.yml
  #when: not ignite_installed.stat.exists

- name: Update ignite configs
  include: configure.yml

- name: Autostart set up
  include: autostart.yml

