---

#- name: Hadoop cluster
# Deploy & configure hadoop on cluster
#- name: Hadoop cluster provisioning
#  hosts: hadoop_all
#  user: user1
#  sudo: yes
#  roles:
#    - hadoop

#- name: Prepare for Hive metastore
#  hosts: hadoop_master
#  user: user1
#  sudo: yes
#  roles:
#    - metastore

- name: Install postgresql metastore
  hosts: hadoop_master
  user: user1
  sudo: yes
  vars_files:
   - ./roles/metastore/group_vars/metastore
  roles:
   - ANXS.postgresql




