---
spark_home: /opt/spark
spark_version: 2.3.0
spark_hadoop_version: 2.7
spark_mirrors: [ "http://apache-mirror.rbc.ru/pub/apache/spark/spark-{{ spark_version }}/spark-{{ spark_version }}-bin-hadoop{{ spark_hadoop_version }}.tgz", "http://mirror.linux-ia64.org/apache/spark/spark-{{ spark_version }}/spark-{{ spark_version }}-bin-hadoop{{ spark_hadoop_version }}.tgz" ]


spark_user: hadoop
spark_group: hadoop
spark_user_home: /home/{{ spark_user }}