---

- name: Add a fast check to speed reconfiguration
  stat: path="{{ spark_home }}/spark-{{ spark_version }}"
  register: spark_installed


- name: Download and copy files to destination
  include: download.yml
  #when: not spark_installed.stat.exists

- name: Remove symlink
  file:
   path: "{{ spark_home }}"
   state: absent

- name: create link to spark
  file:
    src: '{{ spark_home }}-{{ spark_version }}'
    dest: '{{ spark_home }}'
    state: link
    force: yes
    owner: '{{ spark_user }}'
    group: '{{ spark_group }}'


- name: create link to spark
  file:
    src: '{{ spark_home }}-{{ spark_version }}'
    dest: '{{ spark_home }}'
    state: link
    force: yes
    owner: '{{ spark_user }}'
    group: '{{ spark_group }}'

- name: Open spark ports
  include: open-ports.yml

- name: Configuration changes
  include: configure.yml

- name: Autostart set up
  include: autostart.yml

