---

- name: Copy service files
  template:
    src: 'templates/etc/systemd/system/{{ item }}'
    dest: '/etc/systemd/system/{{ item }}'
    sudo: yes
    force: true
    ##mode: 0755
  with_items:
      - hbase-master.service
      - hbase-regionserver.service

- name: Activate master daemons
  when: '"hbase_master" in hadoop_type_of_node'
  service:
    name: '{{ item }}'
    enabled: yes
    state: reloaded
    state: started
  with_items:
      - hbase-master
      - hbase-regionserver

- name: Activate slave daemons
  when: '"hbase_regionserver" in hadoop_type_of_node'
  service:
    name: '{{ item }}'
    enabled: yes
    state: reloaded
    state: started
  with_items:
      - hbase-master
      - hbase-regionserver
