---

- name: Stop hbase services
  when: '"hbase_master" in group_names'
  service:
    name: '{{ item }}'
    enabled: false
    state: stopped
  with_items:
      - hbase-master
      - hbase-regionserver


- name: Copy service files
  template:
    src: 'templates/etc/systemd/system/{{ item }}'
    dest: '/etc/systemd/system/{{ item }}'
#    sudo: yes
    force: true
    ##mode: 0755
  with_items:
      - hbase-master.service
      - hbase-regionserver.service

- name: Activate hbase master daemons
  when: '"hbase_master" in group_names'
  systemd:
    name: '{{ item }}'
    enabled: yes
    state: reloaded
    state: restarted
  with_items:
      - hbase-master

- name: Activate hbase regionservers
  when: '"hbase_regionservers" in group_names'
  systemd:
    name: '{{ item }}'
    enabled: yes
    state: reloaded
    state: restarted
  with_items:
      - hbase-regionserver
