---

- name: Download and copy files to destination
  include: download.yml

- name: Open hbase ports
  include: open-ports.yml

- name: Configuration changes
  include: configure.yml

# ToDo: set up zookeeper first
- name: Autostart set up
  include: autostart.yml

