---

- name: Copy service files
  template:
    src: 'templates/etc/systemd/system/hive-metastore.service'
    dest: '/etc/systemd/system/hive-metastore.service'
    mode: 664
    force: true

- name: Activate metastore service as a daemon
  service:
    name: hive-metastore
    enabled: yes
    state: reloaded
    state: started

