---
#- name: Open postgresql port
#  iptables: chain=INPUT jump=ACCEPT protocol=tcp destination_port={{item}}
#  ignore_errors: yes
#  with_items:
#  - 5432
#
#- name: Restart networking service
#  service: name=network state=restarted
- name: create hive lib directory
  file:
    path: "{{ hive_home }}/lib/"
    owner: hadoop
    state: directory

- name: download postgres driver to hive lib
  become_user: hadoop
  copy: src="postgresql-9.4.1209.jre7.jar" dest={{ hive_home }}/lib/postgresql-9.4.1209.jre7.jar

- name: Ensure that PostreSQL service is running
  systemd:
    name: postgresql
    enabled: yes
    state: restarted

- name: Create new empty metastore db
  shell: "createdb hive_metastore --username hadoop"
  become_user: hadoop

- name: Init metastore
  become_user: hadoop
  command: "{{ hive_home }}/bin/schematool -initSchemaTo {{ metastore_version }} -dbType postgres"

