---
- name: Stop metastore daemon
  service:
    name: hive-metastore
    enabled: yes
    state: stopped

- name: Remove old metastore db
  shell: "dropdb --if-exists hive_metastore --username postgres"
  become: true
  become_user: postgres



